### ISSUE TITLE
Random note on current buffer

### ISSUE THREAD

**Issue by ykgoon** [mwfogleman/org-randomnote#10]
If it can't already do that, do you accept PR?

**Comment by tasshin** [comment]
I am happy to accept a PR. Ideally PR's wouldn't break or significantly alter existing functionality. Hard to tell without a PR how different org-recollect's code/functionality is from org-randomnote.

Perhaps you'd like to maintain this repo, rather than replacing it? I don't actively use org-randomnote.

**Comment by ykgoon** [comment]
@mwfogleman that's great. I'll code this feature and send a PR first,

I don't mind maintaining this repo. I rather not replace it with a new project, the core intention is pretty much the same.
